export const JOB_ROLES: string[] = [
  'Software Engineer',
  'Frontend Developer',
  'Frontend Engineer',
  'Backend Developer',
  'Fullstack Developer',
  'Mobile Developer',
  'iOS Engineer',
  'Android Engineer',
  'DevOps Engineer',
  'Data Engineer',
  'Data Scientist',
  'Machine Learning Engineer',
  'AI Engineer',
  'Cloud Engineer',
  'Security Engineer',
  'QA Engineer',
  'Automation Engineer',
  'Product Manager',
  'Project Manager',
  'Scrum Master',
  'Business Analyst',
  'UI/UX Designer',
  'Graphic Designer',
  'Solutions Architect',
  'System Administrator',
  'Technical Support Specialist',
  'Database Administrator',
  'Network Engineer',
  'IT Support Specialist',
  'Site Reliability Engineer',
  'Technical Writer',
  'Engineering Manager',
  'CTO',
  'CIO',
  'Head of Engineering',
  'Software Architect',
  'Game Developer',
  'Embedded Systems Engineer',
  'Hardware Engineer',
  'Robotics Engineer',
  'Blockchain Developer',
  'Smart Contract Developer',
  'Cybersecurity Analyst',
  'Ethical Hacker',
  'SEO Specialist',
  'Digital Marketing Manager',
  'Content Strategist',
  'Sales Engineer',
  'Customer Success Manager',
  // Administrative & Office Support
  'Administrative Assistant',
  'Office Administrator',
  'Office Manager',
  'Receptionist',
  'Executive Assistant',
  'Personal Assistant',
  'Secretary',
  'Clerical Assistant',
  'Data Entry Clerk',
  'Document Control Specialist',

  // HR & People Admin
  'HR Administrator',
  'HR Coordinator',
  'HR Assistant',
  'HR Officer',
  'Payroll Administrator',
  'Recruitment Administrator',
  'Talent Acquisition Coordinator',
  'Training & Development Administrator',

  // Finance & Business Admin
  'Accounts Administrator',
  'Accounts Payable Clerk',
  'Accounts Receivable Clerk',
  'Billing Administrator',
  'Finance Assistant',
  'Payroll Clerk',
  'Purchasing Administrator',
  'Procurement Coordinator',
  'Contracts Administrator',
  'Accountant',
  'Financial Analyst',
  'Business Analyst',
  'Operations Administrator',
  'Logistics Coordinator',
  'Supply Chain Administrator',

  // Healthcare & Education Admin
  'Medical Secretary',
  'Hospital Administrator',
  'Clinic Administrator',
  'School Administrator',
  'Education Program Coordinator',
  'Academic Registrar',
  'Student Services Administrator',
  'Admissions Coordinator',
  'Library Assistant',
  'Research Administrator',

  // Legal & Compliance Admin
  'Legal Secretary',
  'Paralegal Administrator',
  'Compliance Administrator',
  'Governance Coordinator',
  'Risk & Compliance Assistant',

  // IT & Systems Admin
  'IT Administrator',
  'Systems Administrator',
  'Network Administrator',
  'Database Administrator',
  'Cloud Administrator',
  'Security Administrator',
  'Helpdesk Administrator',

  // Specialist Admin Roles
  'Project Administrator',
  'Sales Administrator',
  'Marketing Administrator',
  'Events Administrator',
  'Facilities Administrator',
  'Logistics Administrator',
  'Travel Administrator',
  'Customer Service Administrator',
];
